/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stickymemories;

import java.util.Date;
import javax.swing.JPanel;

/**
 *
 * @author bernardovieira
 */
public class ReminderPanel extends javax.swing.JPanel {

    private final JPanel master;
    /**
     * Creates new form ReminderPanel
     */
    public ReminderPanel(JPanel panel) {
        initComponents();
        
        master = panel;
        jDateChoser.getJCalendar().setMinSelectableDate(new Date());
        
        JSpinHour.setValue(11);
        JSpinHour.setMinimum(0);
        JSpinHour.setMaximum(23);
        JSpinMinute.setMinimum(0);
        JSpinMinute.setMaximum(59);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChoser = new com.toedter.calendar.JDateChooser();
        removeReminderButton = new javax.swing.JButton();
        JSpinHour = new com.toedter.components.JSpinField();
        hoursLabel = new javax.swing.JLabel();
        JSpinMinute = new com.toedter.components.JSpinField();
        minutesLabel = new javax.swing.JLabel();

        jDateChoser.setToolTipText("Config the reminder");
        jDateChoser.setDateFormatString("dd/MM/yyyy");
        jDateChoser.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        jDateChoser.setOpaque(false);

        removeReminderButton.setText("jButton4");
        removeReminderButton.setMaximumSize(new java.awt.Dimension(30, 30));
        removeReminderButton.setMinimumSize(new java.awt.Dimension(30, 30));
        removeReminderButton.setPreferredSize(new java.awt.Dimension(30, 30));
        removeReminderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeReminderButtonActionPerformed(evt);
            }
        });

        JSpinHour.setOpaque(false);

        hoursLabel.setFont(new java.awt.Font("Monaco", 1, 16)); // NOI18N
        hoursLabel.setText("H");

        minutesLabel.setFont(new java.awt.Font("Monaco", 1, 16)); // NOI18N
        minutesLabel.setText("M");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jDateChoser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JSpinHour, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hoursLabel)
                        .addGap(18, 18, 18)
                        .addComponent(JSpinMinute, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(minutesLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(removeReminderButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDateChoser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(minutesLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JSpinHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JSpinMinute, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(hoursLabel)))
            .addComponent(removeReminderButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void removeReminderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeReminderButtonActionPerformed
        // TODO add your handling code here:
        AddNotePanel.panel_reminders.remove(this);
        AddNotePanel.panel_reminders.invalidate();
        AddNotePanel.panel_reminders.validate();
        AddNotePanel.panel_reminders.repaint();
    }//GEN-LAST:event_removeReminderButtonActionPerformed

    public int getHour()
    {
        return JSpinHour.getValue();
    }
    public int getMinute()
    {
        return JSpinMinute.getValue();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.components.JSpinField JSpinHour;
    private com.toedter.components.JSpinField JSpinMinute;
    private javax.swing.JLabel hoursLabel;
    private com.toedter.calendar.JDateChooser jDateChoser;
    private javax.swing.JLabel minutesLabel;
    private javax.swing.JButton removeReminderButton;
    // End of variables declaration//GEN-END:variables
}
