
package stickymemories.frames;

import java.util.Date;
import javax.swing.JPanel;
import stickymemories.core.Constants;

/**
 *
 * @author bernardovieira
 */
public class ReminderPanel extends javax.swing.JPanel {
    private final JPanel master;
    private int id;

    public ReminderPanel(JPanel panel, int id) {
        initComponents();
        
        this.id = id;
        
        master = panel;
        jDateChoser.getJCalendar().setMinSelectableDate(new Date());
        
        JSpinHour.setValue(11);
        JSpinHour.setMinimum(0);
        JSpinHour.setMaximum(23);
        JSpinMinute.setMinimum(0);
        JSpinMinute.setMaximum(59);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChoser = new com.toedter.calendar.JDateChooser();
        removeReminderButton = new javax.swing.JButton();
        JSpinHour = new com.toedter.components.JSpinField();
        hoursLabel = new javax.swing.JLabel();
        JSpinMinute = new com.toedter.components.JSpinField();
        minutesLabel = new javax.swing.JLabel();

        jDateChoser.setToolTipText("Config the reminder");
        jDateChoser.setDateFormatString("dd/MM/yyyy");
        jDateChoser.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        jDateChoser.setOpaque(false);

        removeReminderButton.setBackground(Constants.colorBackground);
        removeReminderButton.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        removeReminderButton.setText("X");
        removeReminderButton.setMaximumSize(new java.awt.Dimension(30, 30));
        removeReminderButton.setMinimumSize(new java.awt.Dimension(30, 30));
        removeReminderButton.setOpaque(false);
        removeReminderButton.setPreferredSize(new java.awt.Dimension(30, 30));
        removeReminderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeReminderButtonActionPerformed(evt);
            }
        });

        JSpinHour.setOpaque(false);

        hoursLabel.setFont(new java.awt.Font("Monaco", 1, 16)); // NOI18N
        hoursLabel.setText("H");

        minutesLabel.setFont(new java.awt.Font("Monaco", 1, 16)); // NOI18N
        minutesLabel.setText("M");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jDateChoser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JSpinHour, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hoursLabel)
                        .addGap(18, 18, 18)
                        .addComponent(JSpinMinute, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(minutesLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeReminderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDateChoser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(minutesLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JSpinHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JSpinMinute, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(hoursLabel))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(removeReminderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void removeReminderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeReminderButtonActionPerformed
        AddNotePanel.remindersList.remove(this.id);
        AddNotePanel.outer_p.remove(this);
        AddNotePanel.outer_p.invalidate();
        AddNotePanel.outer_p.validate();
        AddNotePanel.outer_p.repaint();
        System.out.println("Removi o reminder:"+this.id);
    }//GEN-LAST:event_removeReminderButtonActionPerformed

    public int getHour(){
        return JSpinHour.getValue();
    }
    
    public int getMinute(){
        return JSpinMinute.getValue();
    }
    
    public void setTime(int year, int month, int day, int hour, int minute){
        jDateChoser.setDate(new Date(year, month-1, day));
        System.out.println("Setei o jDateChoser "+(year)+"y:");
        JSpinHour.setValue(hour);
        JSpinMinute.setValue(minute);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.components.JSpinField JSpinHour;
    private com.toedter.components.JSpinField JSpinMinute;
    private javax.swing.JLabel hoursLabel;
    public com.toedter.calendar.JDateChooser jDateChoser;
    private javax.swing.JLabel minutesLabel;
    private javax.swing.JButton removeReminderButton;
    // End of variables declaration//GEN-END:variables
}
